version: "3.8"

services:

  consul:
    image: docker.io/hashicorp/consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"

  order-service:
    image: asw-project-23-24/order-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-service
    deploy:
      replicas: 2
    depends_on:
      - "consul"
      - "order-service-db"

  product-service:
    image: asw-project-23-24/product-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: product-service
    deploy:
      replicas: 2
    depends_on:
      - "consul"
      - "product-service-db"

  order-validation-service:
    image: asw-project-23-24/order-validation-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-validation-service
    deploy:
      replicas: 2
    depends_on:
      - "consul"

  api-gateway:
    image: asw-project-23-24/api-gateway
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    depends_on:
      - "consul"

  order-service-db:
    image: postgres
    environment:
      POSTGRES_USER: ${ORDER_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${ORDER_POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - order-service-db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  product-service-db:
    image: postgres
    environment:
      POSTGRES_USER: ${PRODUCT_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${PRODUCT_POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - product-service-db:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  order-validation-service-db:
    image: postgres
    environment:
      POSTGRES_USER: ${ORDER_VALIDATION_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${ORDER_VALIDATION_POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - order-validation-service-db:/data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  product-service-db:
  order-service-db:
  order-validation-service-db:
  pgadmin:

