version: "3.8"

services:

  consul:
    container_name: consul
    image: docker.io/hashicorp/consul
    networks:
      - asw-project
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"

  order-service:
    container_name: order-service
    image: asw-project-23-24/order-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-service
    networks:
      - asw-project
    depends_on:
      - "consul"
      - "order-service-db"

  product-service:
    container_name: product-service
    image: asw-project-23-24/product-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: product-service
    networks:
      - asw-project
    depends_on:
      - "consul"
      - "product-service-db"

  order-validation-service:
    container_name: order-validation-service
    image: asw-project-23-24/order-validation-service
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-validation-service
    networks:
      - asw-project
    depends_on:
      - "consul"

  api-gateway:
    container_name: api-gateway
    image: asw-project-23-24/api-gateway
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    networks:
      - asw-project
    depends_on:
      - "consul"

  order-service-db:
    container_name: order-service-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - order-service-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - asw-project
    restart: unless-stopped

  product-service-db:
    container_name: product-service-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - product-service-db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - asw-project
    restart: unless-stopped

networks:
  asw-project:
    driver: bridge


volumes:
  product-service-db:
  order-service-db:
  pgadmin:

