# application.yml 
--- 
spring: 
  application: 
    name: api-gateway
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        healthCheckCriticalTimeout: 45s
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false

    # spring cloud gateway routes 
    gateway:
      discovery:
        locator:
          # spring.cloud.gateway.discovery.locator.enabled abilita la definizione implicita di rotte 
          # sulla base dei servizi registrati nel servizio di service discover (default=false) 
          # enabled: true       
          enabled: false
      routes:
      - id: orderservice_route
        uri: lb://order-service
        predicates:
        - Path=/order-service/**
        filters:
        - StripPrefix=1
      - id: productservice_route
        uri: lb://product-service
        predicates:
        - Path=/product-service/**
        filters:
        - StripPrefix=1
      - id: ordervalidationservice_route
        uri: lb://order-validation-service
        predicates:
        - Path=/order-validation-service/**
        filters:
        - StripPrefix=1
    
server: 
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080

management: 
  endpoint.gateway.enabled: true 
  endpoints.web.exposure.include: info,health,gateway,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.gateway: INFO
