# application.yml 
--- 
spring: 
  application: 
    name: ordervalidationservice
  output:
    ansi:
      enabled: ALWAYS
  spring:
    cloud:
      consul:
        host: consul
        port: 8500
        discovery:
          instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
          healthCheckPath: /actuator/health
          healthCheckInterval: 10s
          healthCheckCriticalTimeout: 45s
          queryPassing: true
      loadbalancer:
        ribbon.enabled: false

server:
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080
#  port: 8083 
  # per swagger dietro un api gateway 
  forward-headers-strategy: framework
  
# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false
