# application.yml
--- 
spring: 
  application: 
    name: productservice
  output:
    ansi:
      enabled: ALWAYS
      
server: 
  port: 8080
#  port: 8080
#  port: 8082 
  # per swagger dietro un api gateway 
  forward-headers-strategy: framework
  
# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false
